### ISSUE TITLE
Allow arbitrary denominators

### ISSUE THREAD

**Issue by paf31** [lumihq/purescript-fixed-precision#1]
Powers of ten are nice for many use cases, but powers of two could be optimized to use shift operations inside of integer division (for example).

**Comment by hdgarrood** [comment]
It's perhaps worth noting that using powers of two, five, or ten makes converting to/from String without losing information a bit easier, since a fraction will have a nonterminating decimal representation whenever the denominator (in reduced form) has any prime factors other than two or five.

**Comment by hdgarrood** [comment]
In practice, this data type is used almost exclusively for currency, so we basically always want powers of ten for denominators. There doesn't seem to be a demand for this, so I think I'm going to close it for now.
