### ISSUE TITLE
Don't default to zero when parsing an empty string

### ISSUE THREAD

**Issue by jxv** [lumihq/purescript-fixed-precision#15]
I expect this to return Nothing.

```
 > fromString "" :: Maybe (Fixed P100)
 (Just (fromString "0.00" :: PfromString "100"))
```

With a space it does.

```
 > fromString " " :: Maybe (Fixed P100)
 Nothing
```

**Comment by hdgarrood** [comment]
This is behaviour inherited from `purescript-bigints`, which is in turn a basic wrapper around the npm package `big-integer`, where this appears to be the intended behaviour, so perhaps it does make sense to address this here.

**Comment by hdgarrood** [comment]
https://github.com/sharkdp/purescript-bigints/issues/23
