### ISSUE TITLE
Can't parse negative numbers

### ISSUE THREAD

**Issue by hdgarrood** [lumihq/purescript-fixed-precision#26]
```
> fromString "-3" :: Maybe (Fixed P100)
Nothing
```

:fearful:

**Comment by arthurxavierx** [comment]
Looks like [this](https://github.com/lumihq/purescript-fixed-precision/blob/master/src/Data/Fixed.purs#L353) is the culprit 😓 
```purescript
fromString str =
  let
    ...
    isDigit = between '0' '9'
    wholeDigits = StringCU.countPrefix isDigit str
    ...
```

**Comment by hdgarrood** [comment]
Yeah, this is my bad. I also blame the `Arbitrary` type class for not including any negative numbers in the `Number` instance. Working on this now.

**Comment by arthurxavierx** [comment]
Oh I didn't want to blame anyone, was just pointing out where in the code the bug could be arising from :)

**Comment by hdgarrood** [comment]
Oh don't worry, I didn't read it that way!

**Comment by hdgarrood** [comment]
Yikes, look at this:
```
> map negate (fromString "2.34" :: Maybe (Fixed P100))
(Just (fromString "-3.66" :: PfromString "100"))
```

**Comment by arthurxavierx** [comment]
That's probably from the broken `toString` function, isn't it?

**Comment by arthurxavierx** [comment]
Yeah, it seems to work just fine in your branch from #27.

**Comment by hdgarrood** [comment]
Yeah, it was using the wrong kind of division when converting to string - it was rounding towards negative infinity when we wanted it to round towards zero.
