### ISSUE TITLE
Fixed isn't a Semiring

### ISSUE THREAD

**Issue by paf31** [lumihq/purescript-fixed-precision#8]
Quickcheck reveals the following properties don't actually hold:

- Associativity of multiplication
- Left and right distributivity

We might want to consider dropping `Semiring` and only providing a (commutative) additive `Monoid`. Multiplication would have to be provided as a function, just like we do for division.

We could perhaps provide an unsafe `Semiring` around a `newtype` for compatibility purposes, but I doubt many people are using this library anyway.

**Comment by hdgarrood** [comment]
For documentation, the following is probably a good example for illustrating why/how multiplication isn't associative:

```
> lift3 (\x y z -> (x * y) * z) (fromNumber 0.01) (fromNumber 0.01) (fromNumber 100.0 :: Maybe (Fixed P100))
(Just (fromNumber 0.0 :: P100))

> lift3 (\x y z -> x * (y * z)) (fromNumber 0.01) (fromNumber 0.01) (fromNumber 100.0 :: Maybe (Fixed P100))
(Just (fromNumber 0.01 :: P100))
```

**Comment by hdgarrood** [comment]
On reflection I'd actually prefer to have `Fixed` keep its `Semiring` instance, and even all of its instances up to `EuclideanRing` and perhaps even `DivisionRing`. Those instances wouldn't be any more dodgy than the same instances for `Number`; at least `Fixed` is a genuine commutative monoid under addition, unlike `Number`. We should just document the circumstances in which it fails to satisfy the laws.
